name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cache Bazel download
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: ~/.cache/bazelisk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development
      - uses: actions/checkout@v2
      - name: Build the code
        run: bazel build //...
